// Run with the bundled Node runtime. The shipped app has no dependencies.
const fs=require('fs');
const path=require('path');
const assert=require('assert/strict');
const deps='/Users/praneethnarala/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';
const {chromium}=require(deps+'/playwright');
const JSZip=require(deps+'/jszip');
const {PNG}=require(deps+'/pngjs');
const ROOT=path.resolve(__dirname,'..');
const OUT=path.join(ROOT,'tests','artifacts');fs.mkdirSync(OUT,{recursive:true});
const URL='file://'+path.join(ROOT,'svg-to-png-studio.html');
const results=[];
let browser;
function record(name,detail){results.push({name,detail});console.log('PASS',name,detail||'');}
async function upload(page,text,name='test.svg'){await page.locator('#rs-file-input').setInputFiles({name,mimeType:'image/svg+xml',buffer:Buffer.from(text)});await page.waitForFunction(()=>!document.getElementById('rs-browse').disabled);}
async function ready(page){await page.locator('#rs-generate:not([disabled])').waitFor({timeout:15000});}
async function previewReady(page){await page.waitForFunction(()=>{const i=document.getElementById('rs-preview-img'),c=document.getElementById('rs-preview-caption');return !i.hidden&&i.complete&&i.naturalWidth>0&&!c.textContent.includes('Updating');});}
async function preset(page,value){await page.locator(`input[name="rs-preset"][value="${value}"]`).check({force:true});}
async function zipExport(page,name){await ready(page);const pending=page.waitForEvent('download',{timeout:60000});await page.locator('#rs-generate').click();const download=await pending;const dest=path.join(OUT,name+'.zip');await download.saveAs(dest);await page.locator('#rs-result').waitFor();return JSZip.loadAsync(fs.readFileSync(dest),{checkCRC32:true});}
async function pngExport(page,name){const pending=page.waitForEvent('download',{timeout:60000});await page.locator('#rs-download-png').click();const d=await pending;const dest=path.join(OUT,name+'.png');await d.saveAs(dest);return PNG.sync.read(fs.readFileSync(dest));}
async function verifyZip(zip){const all=Object.keys(zip.files);const metadata=all.filter(x=>x.endsWith('export-manifest.json'));let count=0;
  for(const name of metadata){const m=JSON.parse(await zip.file(name).async('string')),prefix=name.slice(0,-'export-manifest.json'.length);for(const entry of m.outputs){const b=await zip.file(prefix+entry.path).async('nodebuffer');const png=PNG.sync.read(b);assert.equal(png.width,entry.width);assert.equal(png.height,entry.height);if(entry.background!=='transparent'){assert.equal(b[25],2,'opaque PNG must be RGB (no alpha channel): '+entry.path);for(let i=3;i<png.data.length;i+=4)assert.equal(png.data[i],255);}count++;}}
  return count;
}
function bounds(png){let l=png.width,t=png.height,r=-1,b=-1;for(let y=0;y<png.height;y++)for(let x=0;x<png.width;x++){if(png.data[(y*png.width+x)*4+3]>0){l=Math.min(l,x);t=Math.min(t,y);r=Math.max(r,x);b=Math.max(b,y);}}return {l,t,r,b};}
(async()=>{
  browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
  const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true});const page=await context.newPage();const errors=[],requests=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});
  await page.goto(URL);await page.screenshot({path:path.join(OUT,'desktop-empty.png'),fullPage:true});
  assert.equal(await page.locator('#rs-generate').isDisabled(),true);await page.locator('#rs-sample').click();await ready(page);await previewReady(page);await page.screenshot({path:path.join(OUT,'desktop-sample.png'),fullPage:true});
  record('Initial UI and sample ingestion',await page.locator('#rs-engine-note').textContent());
  const web=await zipExport(page,'web');assert.equal(await verifyZip(web),7);const manifest=JSON.parse(await web.file('evergreen/web/site.webmanifest').async('string'));for(const i of manifest.icons)assert(web.file('evergreen/web/'+i.src));const ico=await web.file('evergreen/web/favicon.ico').async('nodebuffer');assert.equal(ico.readUInt16LE(4),3);for(let i=0;i<3;i++){const o=6+16*i,offset=ico.readUInt32LE(o+12),length=ico.readUInt32LE(o+8);assert.equal(PNG.sync.read(ico.subarray(offset,offset+length)).width,ico[o]);}record('Web ZIP: CRC, dimensions, transparency, ICO, manifest');
  await preset(page,'apple');const apple=await zipExport(page,'apple');const appleCount=await verifyZip(apple);for(const p of ['ios','macos']){const base='evergreen/apple/'+p+'/AppIcon.appiconset/';const contents=JSON.parse(await apple.file(base+'Contents.json').async('string'));for(const i of contents.images){const png=PNG.sync.read(await apple.file(base+i.filename).async('nodebuffer'));assert.equal(png.width,parseFloat(i.size)*parseInt(i.scale));}}record('Apple ZIP: asset catalogs and RGB-only PNGs',appleCount+' PNGs');
  await preset(page,'android');const android=await zipExport(page,'android');assert.equal(await verifyZip(android),11);for(const density of ['mdpi','hdpi','xhdpi','xxhdpi','xxxhdpi']){const p=PNG.sync.read(await android.file('evergreen/android/res/mipmap-'+density+'/ic_launcher_foreground.png').async('nodebuffer'));const b=bounds(p),diagonal=Math.hypot(b.r-b.l+1,b.b-b.t+1);assert(diagonal<=p.width*66/108*.8+3);}record('Android ZIP: density sizes, foreground alpha, safe-circle bounds');
  await page.locator('#rs-clear').click();const vector='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect x="40" y="30" width="20" height="40" fill="#ff0000"/></svg>';
  await upload(page,vector,'geometry.svg');await preset(page,'custom');await page.locator('#rs-custom-sizes').fill('200x100');await ready(page);const trimmed=await pngExport(page,'trimmed');assert.equal(trimmed.width,200);assert.equal(trimmed.height,100);let b=bounds(trimmed);assert(Math.abs(b.l-80)<=1);assert(Math.abs(b.r-119)<=1);assert(Math.abs(b.t-10)<=1);assert(Math.abs(b.b-89)<=1);
  await page.locator('#rs-trim').uncheck();const untrimmed=await pngExport(page,'untrimmed');b=bounds(untrimmed);assert(Math.abs(b.l-92)<=1);assert(Math.abs(b.r-107)<=1);record('Alpha trim, aspect ratio, rectangular output and 10% padding');
  await page.locator('#rs-custom-sizes').fill('0, 4097, bad');assert(await page.locator('#rs-generate').isDisabled());assert(await page.locator('#rs-custom-error').isVisible());await page.locator('#rs-custom-sizes').fill('64,64,128x32');await page.locator('#rs-trim').check();await ready(page);const custom=await zipExport(page,'custom');assert.equal(await verifyZip(custom),2);record('Custom validation and size deduplication');
  await upload(page,vector,'geometry.svg');const batch=await zipExport(page,'batch');assert.equal(await verifyZip(batch),4);assert(batch.file('geometry-2/png/icon-64x64.png'));record('Batch export and collision-safe names');
  await page.locator('#rs-custom-sizes').fill('4096,4095,4094,4093');await ready(page);await page.locator('#rs-generate').click();await page.locator('#rs-cancel').click();await ready(page);await page.locator('#rs-custom-sizes').fill('64');const retry=await zipExport(page,'after-cancel');assert.equal(await verifyZip(retry),2);record('Cancellation and successful engine restart');
  await page.locator('#rs-clear').click();await upload(page,'<svg><bad></svg>','invalid.svg');assert(await page.locator('#rs-generate').isDisabled());assert((await page.locator('#rs-alerts').textContent()).includes('invalid XML'));await page.locator('#rs-clear').click();await upload(page,'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10"><script>window.hacked=true</script><foreignObject width="10" height="10"><div xmlns="http://www.w3.org/1999/xhtml">unsafe</div></foreignObject><rect onload="window.hacked=true" width="10" height="10" fill="red"/></svg>','safe.svg');await ready(page);assert.equal(await page.evaluate(()=>window.hacked),undefined);assert((await page.locator('#rs-alerts').textContent()).includes('Event handlers were removed'));record('Invalid SVG handling and active-content sanitization');
  await page.locator('#rs-clear').click();await upload(page,'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><image href="https://assets.example.com/image.png" width="100" height="100"/></svg>','linked.svg');assert(await page.locator('#rs-generate').isDisabled());assert(await page.getByRole('button',{name:'Load linked assets'}).isVisible());assert.equal(requests.length,0);record('No network requests before explicit linked-asset consent');
  const raster=PNG.sync.write(Object.assign(new PNG({width:2,height:2}),{data:Buffer.from([255,0,0,255,255,0,0,255,255,0,0,255,255,0,0,255])}));
  await page.route('https://assets.example.com/image.png',route=>route.fulfill({status:200,headers:{'content-type':'image/png','access-control-allow-origin':'*'},body:raster}));await page.getByRole('button',{name:'Load linked assets'}).click();await ready(page);await zipExport(page,'linked');record('Consent-based CORS asset inlining');
  await page.locator('#rs-clear').click();
  const fontPath='/System/Library/Fonts/Supplemental/Courier New.ttf';
  await page.route('https://assets.example.com/main.css',route=>route.fulfill({status:200,contentType:'text/css',body:'@import "nested.css"; @font-face { font-family:TestEmbedded; src:url("font.ttf") format("truetype"); } text { font-family:TestEmbedded; }'}));
  await page.route('https://assets.example.com/nested.css',route=>route.fulfill({status:200,contentType:'text/css',body:'.back { fill:#00ff00; }'}));
  await page.route('https://assets.example.com/font.ttf',route=>route.fulfill({status:200,contentType:'font/ttf',body:fs.readFileSync(fontPath)}));
  const beforeCSS=requests.length;
  await upload(page,'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><style>@import url("https://assets.example.com/main.css");</style><rect class="back" width="100" height="100"/><text x="10" y="55" font-size="20">ART</text></svg>','styles.svg');
  assert.equal(requests.length,beforeCSS);await page.getByRole('button',{name:'Load linked assets'}).click();await ready(page);assert(requests.includes('https://assets.example.com/main.css'));assert(requests.includes('https://assets.example.com/nested.css'));assert(requests.includes('https://assets.example.com/font.ttf'));const styled=await pngExport(page,'linked-styles');const green=(32*styled.width+8)*4;assert(styled.data[green+1]>240);assert(styled.data[green]<10);record('Linked CSS, nested relative import, and font embedding');
  await page.locator('#rs-clear').click();await upload(page,'<svg xmlns="http://www.w3.org/2000/svg" width="2in" height="1in"><rect width="192" height="96" fill="red"/></svg>','units.svg');await ready(page);assert((await page.locator('#rs-files').textContent()).includes('192 × 96'));record('SVG dimensions from physical width/height units');
  await page.locator('#rs-clear').click();await upload(page,'<svg xmlns="http://www.w3.org/2000/svg" viewBox="-50 -25 100 50"><defs><linearGradient id="g"><stop stop-color="red"/><stop offset="1" stop-color="blue"/></linearGradient></defs><style>.art{fill:url(#g)}</style><rect class="art" x="-50" y="-25" width="100" height="50"/></svg>','negative.svg');await ready(page);const gradient=await pngExport(page,'negative-gradient');assert(bounds(gradient).r>0);record('Negative viewBox, internal CSS and gradient references');
  await page.setViewportSize({width:390,height:844});await previewReady(page);await page.screenshot({path:path.join(OUT,'mobile.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));assert((await page.locator('#rs-preview-img').getAttribute('alt')).includes('negative.svg'));await page.locator('#rs-paste-open').click();await page.screenshot({path:path.join(OUT,'mobile-paste.png'),fullPage:true});await page.keyboard.press('Escape');assert.equal(await page.locator('#rs-paste-dialog').isVisible(),false);record('390px mobile layout, paste dialog and Escape keyboard behavior');
  assert.deepEqual(errors,[]);record('No uncaught browser errors');
  const fallback=await context.newPage();await fallback.addInitScript(()=>{window.Worker=undefined;window.OffscreenCanvas=undefined;});await fallback.goto(URL);await fallback.locator('#rs-sample').click();await ready(fallback);const fallbackZip=await zipExport(fallback,'fallback');assert.equal(await verifyZip(fallbackZip),7);record('Worker-free fallback with full Web export');
  await page.setViewportSize({width:1440,height:1100});await page.locator('#rs-clear').click();await page.locator('#rs-reset').click();
  await page.locator('#rs-file-input').setInputFiles(Array.from({length:20},(_,i)=>({name:'batch-'+i+'.svg',mimeType:'image/svg+xml',buffer:Buffer.from(vector)})));await ready(page);const largeBatch=await zipExport(page,'20-file-batch');assert.equal(await verifyZip(largeBatch),140);record('140-PNG batch across 20 SVGs');
  await browser.close();browser=null;fs.writeFileSync(path.join(OUT,'test-results.json'),JSON.stringify(results,null,2));console.log('ALL',results.length,'CHECKS PASSED');
})().catch(async e=>{console.error(e);fs.writeFileSync(path.join(OUT,'test-results.json'),JSON.stringify({results,error:e.stack},null,2));await browser?.close();process.exit(1);});
